
export const COMMON_CONSTANTS = {
  //ALL_URL_VALID_CHARACTERS:"abcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=",
  NOTIFICATION_DURATION_MILLISECONS: 3000,
  NOTIFICATION_ERROR_DURATION_MILLISECONS: 10000

};

