
export const COMMON_CONSTANTS = {

  PLAY_CHESS_BOARD_ROWS: 8,
  PLAY_CHESS_BOARD_COLUMNS: 8,

  LOGO_CHESS_BOARD_ROWS: 3,
  LOGO_CHESS_BOARD_COLUMNS: 8,

  NOTIFICATION_DURATION_MILLISECONS: 3000,
  NOTIFICATION_ERROR_DURATION_MILLISECONS: 10000,

  MAX_USERNAME_LENGTH: 10

};

